### ISSUE TITLE
Can view/complete lesson before it is available

### ISSUE THREAD

**Issue by bor0** [woocommerce/sensei-content-drip#112]
This is a regression caused by https://github.com/woocommerce/sensei-content-drip/pull/108.

With that patch:
<img width="774" alt="screen shot 2016-11-05 at 16 54 16" src="https://cloud.githubusercontent.com/assets/1620929/20031493/a5055984-a378-11e6-95e8-be23a6f0b63a.png">

Without that patch:
<img width="780" alt="screen shot 2016-11-05 at 16 54 05" src="https://cloud.githubusercontent.com/assets/1620929/20031495/ab7bdd56-a378-11e6-9df2-f6991f0a7bbd.png">

**Comment by pgk** [comment]
fixed in #113
