### ISSUE TITLE
Please use 'sensei_single_lesson_content_inside_after' instead of 'sensei_lesson_single_meta'

### ISSUE THREAD

**Issue by lvnilesh** [woocommerce/sensei-content-drip#119]
Sensei complains...

SENSEI: The hook 'sensei_lesson_single_meta', has been deprecated since '1.9.0'.Please use 'sensei_single_lesson_content_inside_after' instead. in /var/www/html/wp-content/plugins/sensei/includes/sensei-functions.php on line 208

Appreciate your help with an update.

I see a reference here https://github.com/woocommerce/sensei-content-drip/blob/e72d0fba85e2131f137bf9132dcd7b323e46e8e6/includes/class-scd-ext-lesson-frontend.php#L161

**Comment by pgk** [comment]
@lvnilesh correct, it is a deprecation warning. In the case of Sensei Content Drip, it is not calling `do_action` which would trigger the deprecation warning, it is removing any registered action. It is probably another plugin. Possibly Sensei Media Attachements https://github.com/woocommerce/sensei-media-attachments/issues/13
