### ISSUE TITLE
Certain time formats still cause fatal errors

### ISSUE THREAD

**Issue by danjjohnson** [woocommerce/sensei-content-drip#120]
Following on from https://github.com/woocommerce/sensei-content-drip/issues/103

Steps to reproduce:
1. Switch site language to Dutch
2. Set the date format to 'j F Y'
3. Create a lesson and assign it to a course.
4. Set the drip date to any date where the name of the month is not the same as the English name (e.g. 2 maart 2017)

When you update the lesson you get a fatal error:

Fatal error: Call to a member function getTimestamp() on a non-object in wp-content/plugins/sensei-content-drip/includes/class-scd-ext-lesson-admin.php on line 329

because `DateTime::createFromFormat( 'j F Y', '2 maart 2017' );` returns `false` (F only works with English)

See: http://stackoverflow.com/questions/36498186/php-datetimecreatefromformat-and-multi-languages

507509-zd-woothemes

**Comment by danjjohnson** [comment]
Closing and adding to original issue

**Comment by pgk** [comment]
Reopening this, conversation continues here. Suggest we experiment, adding a filter for translating week names etc to English, possibly implement some default mappings from -> to lang although this might end up being rather

**Comment by aheckler** [comment]
526036-zd-woothemes

**Comment by pgk** [comment]
@danjjohnson I think this will work more predictably if we do not localize this date option. I think it should always be formatted like e.g. `2017/01/31` (full year, month, day)

**Comment by danjjohnson** [comment]
Sounds fine to me. If people ask about it we can tell them that non-English date names cause errors.

**Comment by aheckler** [comment]
523847-zd-woothemes
