### ISSUE TITLE
Undripped content should not be available if Access Permissions is unchecked

### ISSUE THREAD

**Issue by aheckler** [woocommerce/sensei-content-drip#121]
I'm not 100% sure this is a bug (might be expected behavior), but...

To repro:

1. Uncheck "Access Permissions" under Sensei > Settings.
2. Add a course and a lesson within that course.
3. Set lesson to drip on a specific date in the future.
4. If you're taking the course, you'll see the "lesson will become available warning."
5. If you're logged out, you'll see the lesson content.

I could go either way here. On the one hand, when you uncheck Access Permissions, you'd rightly expect anyone to be able to see the lesson content. On the other hand, it seems unintuitive and backwards that logged out people can see something that logged in people can't.

Maybe if something is set to be dripped, we restrict access even for logged out people if the Access Permissions box is unchecked? Or maybe we make it impossible to drip anything if Access Permissions is unchecked?

521781-zd-woothemes

**Comment by donnapep** [comment]
The _Access Permissions_ setting should only be taken into account for content that has already dripped. If a lesson isn't available yet, then the lesson should not be visible either logged in or logged out users, regardless of whether or not _Access Permissions_ is checked or unchecked.

**Comment by alexsanford** [comment]
Another note: the lesson content is also available to logged-in users who are not yet taking the course. It should not be available to them either.
