### ISSUE TITLE
Don't rely on folder name to check if Sensei is active

### ISSUE THREAD

**Issue by danjjohnson** [woocommerce/sensei-content-drip#125]
Same issue as Certificates used to have:
https://github.com/woocommerce/sensei-certificates/issues/83

If the folder name for Sensei is not `woothemes-sensei` or `sensei` it will fail the `sensei_active_check` and Content Drip will not work.

**Comment by richardmtl** [comment]
This one came up again in 1147668-zen

**Comment by richardmtl** [comment]
Again in 1187180-zen

**Comment by alexsanford** [comment]
Fixed in #146
