### ISSUE TITLE
Translation of "Give Access" text doesn't appear 

### ISSUE THREAD

**Issue by amroland** [woocommerce/sensei-content-drip#144]
**Steps to Reproduce**

1. Change the language other than English.
2. Go to Sensei > Learner Management.
3. Click "Manage Learners" on any course.
4. In "Manual Content Drip" panel select a user.
5. Select a lesson.
6. You can see that every translation appears except "Give Access" text.

**Screenshots**

![kepernyofoto 2018-11-14 - 17 23 29](https://user-images.githubusercontent.com/39312392/48575504-64863400-e912-11e8-98a4-5622989d1ba9.png)

In PO language file "Give Access" text has translation already:
![kepernyofoto 2018-11-14 - 17 20 59](https://user-images.githubusercontent.com/39312392/48575547-8d0e2e00-e912-11e8-825f-5516625776fb.png)

**Comment by donnapep** [comment]
Fixed by #157.

**Comment by donnapep** [comment]
@amroland Would appreciate a quick test to ensure this is fixed in the [2.0 beta](https://github.com/woocommerce/sensei-content-drip/releases/tag/version%2F2.0.0-beta.2). Thx!

**Comment by donnapep** [comment]
The fix is in Sensei 2.0, so you need to download the beta as I've linked above and test it there. Thx!

**Comment by amroland** [comment]
@donnapep 
I tested it.
It works. Translation of "Give Access" text appears.
I refreshed PO file with the latest POT file. You can add Hungarian translation to Sensei Content Drip.
[sensei-content-drip-hu_HU.zip](https://github.com/woocommerce/sensei-content-drip/files/2999255/sensei-content-drip-hu_HU.zip)
