### ISSUE TITLE
Lesson order in drip email is wrong for lessons within modules

### ISSUE THREAD

**Issue by alexsanford** [woocommerce/sensei-content-drip#154]
To test:

- Create a course with some modules.
- Add some lessons to the modules.
- Reorder the lessons within the modules, and/or move lessons to other modules.
- Make all the lessons drip today, and manually run the `woo_scd_daily_cron_hook` cron task.
- You should see that the lessons are not ordered in the email the way they are ordered within the course.

**Comment by gkaragia** [comment]
Lessons can be ordered in three different levels:

1. Course
2. Module
3. Lesson

As it is now, in the emails that we send the lessons are orderer only in the lesson level. What we try to achieve with this is to take into consideration all ordering levels. The functionality is implemented in [get_ordered_courses_and_lessons](https://github.com/woocommerce/sensei-content-drip/blob/eef65c3fab3266be47b125e3ed07ba26763680af/includes/class-scd-ext-drip-email.php#L378) method.
