### ISSUE TITLE
Admin user unable to view content of lessons that haven't dripped

### ISSUE THREAD

**Issue by donnapep** [woocommerce/sensei-content-drip#167]
### Steps to Reproduce
- Assign a drip schedule to a lesson that is some date in the future.
- As an admin-level user, start taking the course that lesson is in.
- Browse to the lesson that hasn't dripped yet.

### What I Expected
To be able to view the content of the lesson.

### What Happened Instead
The lesson content is not visible. Instead, there is a message that "This lesson will become available on ...."

This was introduced by #127.

**Comment by richardmtl** [comment]
2346818-zen

The user expected the Teacher to be able to view it as well.
