### ISSUE TITLE
Not working because of version check

### ISSUE THREAD

**Issue by Beezebox** [woocommerce/sensei-content-drip#168]
This is actually an issue and its solution. I just downloaded Sensei LMS Master 2.0.1 + Sensei Drip 2.0.0 and I got an error message saying the Drip plugin needed Sensei 1.11.0 minimum and it was there, but it couldn’t find it.

In ../sensei-content-drip-master/includes/class-scd-ext-dependency-checker.php, line 73, replace:

$search_sensei = array(
‘sensei/sensei.php’, // Sensei 2.x from WordPress.org.
‘sensei/woothemes-sensei.php’, // Sensei 1.x or Sensei 2.x Compatibility Plugin.
‘woothemes-sensei/woothemes-sensei.php’, // Sensei 1.x or Sensei 2.x Compatibility Plugin.
);
with:

$search_sensei = array(
‘sensei-master/sensei-lms.php’, // Sensei 2.x from WordPress.org.
‘sensei/woothemes-sensei.php’, // Sensei 1.x or Sensei 2.x Compatibility Plugin.
‘woothemes-sensei/woothemes-sensei.php’, // Sensei 1.x or Sensei 2.x Compatibility Plugin.
);

**Comment by jom** [comment]
@Beezebox It looks like you are using an old version of Content Drip. Those lines were removed. They are not there in the released 2.0.0 version (they might have been in an earlier beta).

**Comment by Beezebox** [comment]
You're right actually, I downloaded it on gpldl.com and thought it was the same here ^^ Thanks!
