### ISSUE TITLE
[date] notification: can't translate the month/day names

### ISSUE THREAD

**Issue by tarvalian** [woocommerce/sensei-content-drip#56]
For the "This lesson will only become available on [date]" string, the date doesn't reflect the date format for the language set in WordPress.  Looking at the code for this, I'm not sure why it's doing this, as it seems to be the standard PHP date format.  Other dates, such as post dates, show up correctly on the same site.

screenshot: http://cld.wthms.co/14zW6
ticket: https://woothemes.zendesk.com/agent/tickets/246647

**Comment by JanineKall** [comment]
Hi all, I found this old thread because by now (2024) I am still having this problem. Is there any way we can fix this?
