### ISSUE TITLE
Allow the user to disable the email that gets sent out

### ISSUE THREAD

**Issue by dwainm** [woocommerce/sensei-content-drip#60]
The user should be able to disable this for all emails or only a specific email

**Comment by jenhooks** [comment]
Requested in 474422-zd-woothemes

**Comment by lizosting** [comment]
@dwainm did you ever get a solution to this? I am desperate to disable these emails.

**Comment by RubbelDeCatc** [comment]
It's really the best script. Bute because of the update rate these mails are disturbing.

I found a config switch called **_MUTE**
Update messages should stop if you add the following line to your getssl.cfg in .getssl/

`_MUTE=1`

**Comment by danjjohnson** [comment]
@bor0 we should also check the "Disable course notifications" setting in each course, so that the emails can be disabled per course:

![image](https://cloud.githubusercontent.com/assets/1990037/20834631/47c3800e-b88e-11e6-8014-c5c22ff2a48c.png)

**Comment by pgk** [comment]
addressed @danjjohnson 's comment on https://github.com/woocommerce/sensei-content-drip/commit/974e5278c8a48d7ac20cdc39ab99eb1d3b95675c
