### ISSUE TITLE
Course Expiration.

### ISSUE THREAD

**Issue by dwainm** [woocommerce/sensei-content-drip#69]
Continuation from https://github.com/woothemes/sensei/issues/553

http://ideas.woothemes.com/forums/191508-sensei/suggestions/4058235-course-expiration

I think this could be a simple option on a course page, like:

"Access to this course will expire [6] [months] after starting the course." (defaults to [never]).

When a user starts the course, the access period begins, and once the time limit is reached, that user is removed from the course.

**Comment by flabernardez** [comment]
Will be this feature available soon? Thanks so much!

**Comment by jenhooks** [comment]
A user in 1978104-zen has 34 courses on their site, which they offer eight times a year. They need the ability to set a start and end date for each new cohort of students who purchases the course. I think this enhancement would cover the start date component?

**Comment by amouratoglou** [comment]
hi guys any idea when this feature will be ready to use?? we really need it.

**Comment by donnapep** [comment]
@amouratoglou We haven't yet committed to doing this, however, you can [upvote this feature](c/l2EQEYRL-tr/10-course-expiration) on our Trello board.

**Comment by amouratoglou** [comment]
@donnapep found a way to implement it without sensei... will upvote! thanks :)

**Comment by donnapep** [comment]
It's unlikely this will be part of Content Drip. More likely to be part of core Sensei / WCPC. See https://github.com/Automattic/sensei/issues/553.
