### ISSUE TITLE
Search for Learner

### ISSUE THREAD

**Issue by DustinHartzler** [woocommerce/sensei-content-drip#78]
When someone is looking to change something in learner management, you need to scroll for the correct learner in the drop down menu. Since the order is by date of signup and not alphabetical, it makes it a challenge when you have lots of learners.

<img width="257" alt="screen shot 2015-10-08 at 2 25 16 pm" src="https://cloud.githubusercontent.com/assets/2293077/10375801/6f1c2230-6dc8-11e5-9e4e-bf8d79ea492d.png">

Can we make that drop down box similar to the one in the Learner Management sections that allows to type the letters of a Learner?

<img width="323" alt="screen shot 2015-10-08 at 2 24 31 pm" src="https://cloud.githubusercontent.com/assets/2293077/10375785/5a765102-6dc8-11e5-99de-c57ad0d5b464.png">

**Comment by bor0** [comment]
The given drop down allows searching:
<img width="228" alt="screen shot 2016-11-10 at 20 27 06" src="https://cloud.githubusercontent.com/assets/1620929/20191036/1d608ce6-a784-11e6-8d92-787262fd21a2.png">
<img width="240" alt="screen shot 2016-11-10 at 20 27 09" src="https://cloud.githubusercontent.com/assets/1620929/20191037/1d60d5ca-a784-11e6-803b-bf829a07cc2e.png">

So I believe we can close this issue.
