### ISSUE TITLE
Drip email sends you to lesson where you are asked to purchase the course

### ISSUE THREAD

**Issue by danjjohnson** [woocommerce/sensei-content-drip#87]
From ticket: https://woothemes.zendesk.com/agent/tickets/372628

> Your drip notification send you links to lessons. If you follow those and are not logged in, a warning message suggests you buy the course. That is terrible UX and has resulted in lots of support emails for us to handle. It should say "Please log in to access this content" with the log in text linking to the my courses page.

**Comment by donnapep** [comment]
Closing as this needs to be fixed in Sensei, not Sensei Content Drip.
