### ISSUE TITLE
Course start date

### ISSUE THREAD

**Issue by danjjohnson** [woocommerce/sensei-content-drip#88]
Currently, when dripping lessons based on the course start date, this uses the purchase date as the start date.

Several users have requested the ability to set a specific course start date, separate from the purchase date, which will be used as the basis for dripping lessons, so that all learners get them at the same time, regardless of when they purchase the course.

I suspect this could simply be an additional date field in the course edit screen.

**Comment by jenhooks** [comment]
474457-zd-woothemes

**Comment by aheckler** [comment]
515495-zd-woothemes

**Comment by jenhooks** [comment]
A user in 1978104-zen has 34 courses on their site, which they offer eight times a year. They need the ability to set a start and end date for each new cohort of students who purchases the course. I think this enhancement would cover the start date component?

**Comment by tjosm** [comment]
This will be a really useful feature.

**Comment by burtrw** [comment]
Closing this as we are looking to add the functionality in Sensei Pro.
