### ISSUE TITLE
Schedule emails to send at 00:30

### ISSUE THREAD

**Issue by dwainm** [woocommerce/sensei-content-drip#91]
Bring email send time closer to the drip time. Set it to 0:30 server time. 

Allow this to be filtered. Create a doc to that guides users on how to change the email send time.

https://woothemes.zendesk.com/agent/tickets/369429

**Comment by wdfee** [comment]
the guide isn't available anymore. why not make admins able to set the time with another field?

**Comment by donnapep** [comment]
Currently, the emails are scheduled to send at the time that the plugin was installed. If that was 5PM, then the emails won't send until then. We should change this to send at 00:30 server time.

As per https://github.com/woocommerce/sensei-content-drip/issues/91#issuecomment-188851724, a filter isn't necessary here.
