### ISSUE TITLE
Lesson title should not be displayed(?)

### ISSUE THREAD

**Issue by joeridetering** [woocommerce/sensei-content-drip#96]
When the content drip content lessons are not available, the lesson title should not be displayed. How can we manage do solve this? I contacted several developers but it's pretty hard: http://imgur.com/zXYDvoj

**Comment by richardmtl** [comment]
Originally from 410688-zd-woothemes.

**Comment by donnapep** [comment]
This isn't functionality that we want to add to the plugin. By default, the lesson title will be visible but not the lesson content.
